# Generated by Django 2.2.5 on 2019-09-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190914_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='caretask',
        ),
        migrations.RemoveField(
            model_name='task',
            name='medications',
        ),
        migrations.AddField(
            model_name='caretasks',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='medications',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
