# Generated by Django 2.2.5 on 2019-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
