# Generated by Django 2.2.5 on 2019-09-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_isdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
