# Generated by Django 2.2.5 on 2019-09-17 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
