# Generated by Django 2.2.5 on 2019-09-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20190917_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete_time',
            new_name='done_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='isComplete',
        ),
    ]
