# Generated by Django 2.2.5 on 2019-09-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20190917_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dead_line',
            new_name='deadline',
        ),
    ]
