# Generated by Django 2.2.5 on 2019-09-22 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_employeelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dnrs',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='DNR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
    ]
