# Generated by Django 2.2.5 on 2019-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='files',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
