# Generated by Django 2.2.5 on 2019-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_auto_20190925_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='is_excused',
            field=models.BooleanField(default=False),
        ),
    ]
