# Generated by Django 2.2.5 on 2019-12-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='document',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
