# Generated by Django 2.2.5 on 2019-12-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('folders', '0003_cv_dbschecks_dbscherighttoworkrecordscks_identitydocuments_interviewnotes_jobdescription_jobofferlet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBSCheRightToWorkRecordscks',
            new_name='RightToWorkRecordscks',
        ),
    ]
