# Generated by Django 2.2.5 on 2020-02-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='access_to_home',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='accomodation_info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='accomodation_type',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='general_notes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='health_care_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_living_alone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='lat',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='lon',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='private_notes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='', max_length=500),
        ),
    ]
